name: Update File Manifest
on:
  push:
    branches: [main]

jobs:
  update_manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # Critical: Allow write permissions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate File List
        run: |
          # Explicitly navigate to repo root
          cd $GITHUB_WORKSPACE
          python3 scripts/generate_manifest.py

      - name: Commit and Push Manifest
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifest.json
          git commit -m "Update manifest.json"
          git push origin HEAD:
